### ISSUE TITLE
[Question] Update?

### ISSUE THREAD

**Issue by UpcraftLP** [Padwolf/MC-GBB1.8.9#1]
When (if ever) will you update this mot to 1.10 (or 1.11 when LexManos finishes the first Forge release)?
I'd really like to be able to travel in time and relative dimensions in space ;)

**Comment by Padwolf** [comment]
Thanks for the Interest. Before I can update it, I need to finish the mod for 1.8.9. I may try parallel programming it for 1.10 and possibly 1.9 so they are done at the same time, but it will still be a few months at least.
You know, when I think about it, unfortunately the ship won't be able travel it time, at least not yet. Perhaps a better name is RDIS, Relative Dimensions în Space. :-)

**Comment by UpcraftLP** [comment]
well, there weren't any changes in code between 1.9.4 and 1.10.2, except for the new added things (sounds, structures, blocks, items, etc.), so as long as you don't use any of them the 1.10 version should work in 1.9 just fine.

Anyways, I think I keep calling it TARDIS (Teleport away (to) relative dimensions in space) :p

**Comment by Padwolf** [comment]
My plan was to keep calling it a TARDIS,  though I like the idea of using a modified acronym. Perhaps "Temporaly Associated Relative Dimensions in Space", Wth temporaly accessible meaning there is no time travel.
Thanks.

**Comment by UpcraftLP** [comment]
yeah that's a great idea ;D
